#!/bin/bash

reader="zathura"
tmpdir=".path/tmp"
actualdir=`pwd`
directory=`echo "$@" | sed -r "s:(^.*/)[^/]+$:$actualdir/\1:"`
file=`echo "$@" | sed -r "s:.*/([^/]+)$:\1:"`
name=`echo "$file" | sed -r "s:(^.*)\.[^.]*$:\1:"`
extension=`echo "$@" | sed -r "s:^.*(\.[^.]*$):\1:"`
if [[ "$extension" == .pdf ]]; then
  zathura "$file"
else
  cd $HOME/$tmpdir
  tmpfile="$name"".pdf"
  if [[ ! -f "$tmpfile" ]]; then
    soffice --convert-to pdf "$directory""$file" --headless
  fi
  $reader "$tmpfile"
fi
