#!/bin/sh
## zaread - a simple script created by paoloap.

# zaread cache path
ZA_CACHE_DIR="${XDG_CACHE_HOME:-"$HOME"/.cache}/zaread"
# zaread config path
ZA_CONFIG="${XDG_CONFIG_HOME:-"$HOME"/.config}/zaread/zareadrc"

# Default reader, i.e. command, which script uses to open pdf, epub and converted files
READER="zathura"
# Defaults converters, i.e. commands, which script uses to convert files to pdf
MOBI_CMD="ebook-convert"
OFFICE_CMD="soffice"
MD_CMD="md2pdf"
# If you want to use other commands set these vars in $ZA_CONFIG. Some cli
# arguments are hardcoded so some commands won't work. Check that first.

# Sources the variables from config file if exists
# shellcheck disable=1090
[ -f "$ZA_CONFIG" ] && . "$ZA_CONFIG"

# if $ZA_CACHE_DIR doesn't exist, we create it.
[ ! -d "$ZA_CACHE_DIR" ] && mkdir -p "$ZA_CACHE_DIR"

# Exit if called without arguments
if [ "$#" = 0 ]; then
	echo "No files to open."
	exit
fi

if [ "$#" != 1 ]; then
	echo "More than one filename given. Closing."
	exit 1
fi

path="$1"

if [ ! -f "$path" ]; then
	echo "File doesn't exist."
	exit 1
fi

# If set reader isn't in the $PATH, we force the user to choose a pdf reader
# after three wrong commands, the script exits.
# If the user inserts a command that exists but is not a pdf READER then... then fuck her/him.
counter=1
while ! command -v "$READER" >/dev/null; do
	if [ "$counter" -gt 3 ]; then
		echo "'$READER' not in the \$PATH"
		exit 1
	fi

	echo "Set \$READER='$READER' command is not in the \$PATH. Close script, set right command in $ZA_CONFIG and start again or enter valid reader command. ($counter/3)"

	echo "Enter new reader command which will be added to $ZA_CONFIG:"
	read -r READER
	# Not sure if this check is needed
	[ ! -d "$ZA_CONFIG" ] && mkdir -p "$(dirname "$ZA_CONFIG")"
	sed -i '/^[[:space:]]*READER=/d' "$ZA_CONFIG"
	echo "READER=$READER" >>"$ZA_CONFIG"
	echo "READER=$READER appended to $ZA_CONFIG"
	counter=$((counter + 1))
done

echo "\$READER='$READER' is valid. Starting script..."

## create position and file variables ##

# complete file name (path excluded):
file="$(basename "$path")"
echo "Filename: $file"
case "$path" in
# complete directory path:
# if it has been inserted absolute path ($path starts with '/')
/*)
	directory="$(dirname "$path")"
	;;
# else (relative path inserted)
*)
	directory="${PWD}/$(dirname "$path")"
	# directory="$(echo "$dir" | tr -s '/')"
	;;
esac

echo "Directory: $directory"
echo "Path: $directory/$file"

# get file type

# if the file is itself a pdf or an epub, or we already have a pdf converted version,
# then we don't need a converter. But if it's an already converted document, then
# file position is different: we must distinguish between original and converted files
file_mt="$(file --mime-type "$directory/$file")"
file_mt="${file_mt#*: }"
echo "Mime type: $file_mt"

cd "$directory" || {
	echo "Couldn't cd into $directory"
	exit 1
}

# $pdffile is a string composed this way: CRC_BYTECOUNT_$filename.[pdf,epub]
# if the converted file exists, then it's named like $pdffile
pdffile="$(cksum "$file" | sed -E 's/^([0-9]+) ([0-9]+) (.*)$/\1_\2_\3.pdf/')"
echo "Converted pdf filename: $pdffile"

file_converter=""
# If the converted file exists we can just open it.
if [ -f "$ZA_CACHE_DIR/$pdffile" ]; then
	file_converter="none_converted"
else
	case "$file_mt" in
	"application/pdf" | "application/epub+zip")
		# If the file is a pdf or an epub we don't need to convert it.
		file_converter="none_original"
		;;
	"application/vnd.openxmlformats-officedocument.wordprocessingml.document" | \
		"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" | \
		"application/vnd.openxmlformats-officedocument.presentationml.presentation" | \
		"application/msword" | \
		"application/vnd.ms-excel" | \
		"application/vnd.ms-powerpoint" | \
		"application/vnd.oasis.opendocument.text" | \
		"application/vnd.oasis.opendocument.spreadsheet" | \
		"application/vnd.oasis.opendocument.presentation" | \
		"text/csv")
		# If the file is an office file (ooxml or the old format or an
		# opendocument) we convert it using $OFFICE_CMD.
		file_converter="$OFFICE_CMD"
		;;
	"application/octet-stream")

		case "$file" in
		*.mobi)
			# If the file is a mobi ebook we convert it using $MOBI_CMD.
			file_converter="$MOBI_CMD"
			;;
		esac
		;;
	"text/plain")
		case "$file" in
		*.md)
			# If the file is a markdown we convert it using $MD_CMD.
			file_converter="$MD_CMD"
			;;
		esac
		;;
	esac
fi

case "$file_converter" in
"")
	echo "The file format is unsupported."
	exit 2
	;;
"none_original")
	echo "The file is already in PDF format. We just open it."
	"$READER" "$directory/$file"
	;;
"none_converted")
	echo "We already converted this file. We just open it."
	"$READER" "$ZA_CACHE_DIR/$pdffile"
	;;
*)
	# So the file is not a pdf or an epub, and a converted version
	# doesn't exist, but its format may be converted
	if command -v "$file_converter" >/dev/null; then
		echo "We are starting to convert the file \"$file\" using $file_converter"
		# If converter tools are changed in $ZA_CONFIG check calling
		# commands bellow. They may need to be called with different
		# arguments and format.
		case "$file_converter" in
		"$OFFICE_CMD")
			"$OFFICE_CMD" --convert-to pdf "$directory/$file" --outdir "$ZA_CACHE_DIR"
			esac
			mv "$ZA_CACHE_DIR/$tmpfile" "$ZA_CACHE_DIR/$pdffile"
			;;
		"$MOBI_CMD")
			"$MOBI_CMD" "$directory/$file" "$ZA_CACHE_DIR/$pdffile"
			;;
		"$MD_CMD")
			"$MD_CMD" "$directory/$file" -o "$ZA_CACHE_DIR/$pdffile"
			;;
		esac
	else
		echo "The command we need to convert '$file_converter' is not in \$PATH."
		exit 4
	fi
	echo "Now we can open the file $ZA_CACHE_DIR/$pdffile"
	# ...and after the conversion we open the file
	"$READER" "$ZA_CACHE_DIR/$pdffile"
	;;
esac
